### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by heartlex** [break-stuff/cem-plugin-vs-code-custom-data-generator#1]
Hello, i'm not sure to have understood how to use this useful plugin.
- Install via repo manager as a dev dependency in a project (OK)
- create custom-elements-manifest.config.js file and export generateCustomData (correct?)
- edit settings.json introducing html-custom-data.json (where is this file from? is it something inside vsc?)
- tag mapping has to be done manually (correct?)

Thank you for clarifications

**Comment by break-stuff** [comment]
Thank you for reaching out! 

- Before you get started, make sure install and set up the [Custom Elements Manifest Analyzer](https://custom-elements-manifest.open-wc.org/analyzer/getting-started/).
- Create a [config file](https://custom-elements-manifest.open-wc.org/analyzer/config/#config-file)
- Once you do that, you should be able to follow the [usage instructions](https://www.npmjs.com/package/cem-plugin-vs-code-custom-data-generator) in the package.
- When you run the analyzer, you should see a generated file.
- Often times a `.vscode` folder with a `settings.json` file in it already exists at the root of your projects from other plugins or extensions. If not, create one and add a reference to the generated file.

```json
{
  "html.customData": [
    "./vscode.html-custom-data.json"
  ]
}
```

After you restart VS Code you should see autocomplete information. 

Let me know if that helps.

**Comment by heartlex** [comment]
Hi, i've installed custom-elements-manifest/analyzer, but i get  command not found: custom-elements-manifest or  command not found: cem following the instructions on their website

**Comment by break-stuff** [comment]
in your `package.json` file, did you add a script to run the analyzer? It should looks something like:

```json
"analyze": "cem analyze"
```

Once you have that added, you should be able to run `npm run analyze` to run the analyzer.

**Comment by break-stuff** [comment]
Were you able to get it running?

**Comment by break-stuff** [comment]
Let me know if you run into any other issues.
