### ISSUE TITLE
camelCased attribute name picked up instead of kebab-case name

### ISSUE THREAD

**Issue by jaredcwhite** [break-stuff/cem-plugin-vs-code-custom-data-generator#14]
Thanks for such a cool plugin!

I'm working on a JS-based LitElement custom element with JSCode comments, and I have a property called `fixedWidth` which I want to use as `fixed-width` for the HTML attribute. However, the plugin is generating the `vscode.html-custom-data.json` file with `fixedWidth` as the attribute name instead of `fixed-width`. I think it's due to this particular line:

https://github.com/break-stuff/cem-plugin-vs-code-custom-data-generator/blob/d1878573583267364eb8462d9b832ff5b4a11d5d/src/custom-data-generator/generator.ts#L213

If I reverse that to `attr.name || attr.fieldName`, then the json output seems correct to me (but perhaps that would inadvertently cause some other issue I'm not aware of).

Thoughts?

**Comment by break-stuff** [comment]
I think you might be right. Let me do some quick tests and I will push out a change if everything goes well. Thanks!

**Comment by break-stuff** [comment]
Worked like a charm! I just pushed out a patch. Thanks!
