### ISSUE TITLE
Generated File is Empty

### ISSUE THREAD

**Issue by tmcconechy** [break-stuff/cem-plugin-vs-code-custom-data-generator#21]
Hi There,

Hoping this is the right place. Was looking at how shoelace makes the intelisense work and tried to do the same thing.
The results is in this repo but when doing so the `vscode.css-custom-data.json` file just came up empty.

- node 18
- clone https://github.com/infor-design/enterprise-wc

```sh
git checkout 1010-add-schemas
npm i
npx cem analyze
```

Diff -> https://github.com/infor-design/enterprise-wc/pull/new/1010-add-schemas
You can see that `custom-elements.json` looks right but `vscode.html-custom-data.json` is empty.

Any suggestions you can offer? Is this the only tool that puts custom-elements.json in vs code format?
Or any way to debug?

Also should https://github.com/break-stuff/cem-plugin-vs-code-custom-data-generator/blob/main/package.json#L34 be a devDependency ?

Thanks!

**Comment by break-stuff** [comment]
Thanks for reaching out! I'll pull down your PR and take a look.

I don't think there are really any other tools like this out there which is kind of why I built this.

That dependency is actually not a dev dependency because it is used to format the final output files.

**Comment by break-stuff** [comment]
I don't see that branch anymore. Was it deleted?

**Comment by break-stuff** [comment]
Ah, it looks like it was merged into the main branch. It looks like it is generating the file. 

@tmcconechy, I think there may be a problem with the way you are defining attributes. Right now they are all being defined as properties and not as attributes. Is that intended? These aren't defined as reactive properties with attribute definitions, so everything is outputting as camel-case. You may want to try something like this: https://lit.dev/docs/components/properties/#observed-attributes

**Comment by tmcconechy** [comment]
@break-stuff thanks. 

We dont use` lit` though. We are using plain web component attributes/properties and making them reactive via the https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-about/ids-about.ts#L30 area as per the web component spec 

I did find another solution based on what you did and that was to make my own plugin. But the idea in that was to take the file that is produced by `@custom-elements-manifest/analyzer` and convert it to the other format rather than parsing any code. Because the analyzer did work and was able to process my code correctly. Since i only needed tags and attributes. See: https://github.com/infor-design/enterprise-wc/blob/main/scripts/cem-plugin-vscode.mjs 

If you do want to see about getting it working for regular web components i can redo the branch to check out. But if not you can close. Or consider my idea of parsing the output file from ``@custom-elements-manifest/analyzer`

**Comment by break-stuff** [comment]
Interesting... I wonder why the analyzer doesn't create the "attributes" section of the custom elements manifest. I may be able to refactor to grab from the members. The challenge here is that what is being output will not match the attribute names, so VS Code will provide autocomplete for all of your members (all methods and properties), but those won't match your attribute names. For example, your component `ids-week-view` has an attribute called `show-today` and a property called `showToday`. VS Code will display `showToday` as an attribute in the autocomplete, but it won't map correctly within your component.

**Comment by tmcconechy** [comment]
yes interesting @break-stuff - for us we are just using this (for now) for html markup intellisense so would want the `show-today` for the html side. But i could see `showToday` being useful for other use cases like docs. For code we rely on the Ts types.

But ours isnt the only use case. But i can check this in my simple plugin and make sure the camel case version is the one being shown.

**Comment by break-stuff** [comment]
You don't want the camel-case version to be shown. You want the kebab-case attribute so that it correctly aligns with your component's attribute name.

**Comment by break-stuff** [comment]
In order for you to get this working properly, you will need to add the attributes to the jsDoc using the `@attr` or `@attribute` tag shown here.

https://custom-elements-manifest.open-wc.org/analyzer/getting-started/

**Comment by break-stuff** [comment]
Once that is updated, you should be able to use the plugin again.

**Comment by tmcconechy** [comment]
Ok i think we can close this then. Thanks @break-stuff

**Comment by break-stuff** [comment]
Awesome! Feel free to reach out if you get stuck.
